<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_4.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0.0" rpy="1.57 0 -1.57" />
            <geometry>
                <mesh filename="file://$(find scout_description)/meshes/scout_mini_base_link2.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.57 0 1.57" />
          <geometry>
            <mesh filename="file://$(find scout_description)/meshes/scout_mini_base_link2.dae" />
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- base_footprint Link -->
    <link name="base_footprint"/>

    <!-- base_footprint Joint-->
    <joint name="base_link_to_base_footprint" type="fixed">
        <origin xyz = "0 0 -0.2" rpy = "0 0 0"/>
        <parent link = "base_link"/>
        <child link = "base_footprint"/>
    </joint>

    <!-- LiDAR Sensor -->
    <link name="lidar_link">
    <!-- 시각화 -->
        <visual>
            <geometry>
                <cylinder length="0.02" radius="0.07"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="bright_red">
                <color rgba="1 0 0 1"/>
            </material>
        </visual>

    <!-- 충돌 범위 설정-->
        <collision>
            <geometry>
                <cylinder length="0.02" radius="0.07"/>
            </geometry>
        </collision>
    </link>

    <!-- lidar랑 base 연결 -->
    <joint name="lidar_joint" type="fixed">
        <origin xyz="0 0 0.15" rpy="0 0 0"/> <!-- LiDAR를 base_link 위에 30cm 배치 -->
        <parent link="base_link"/>
        <child link="lidar_link"/>
    </joint>

    <!-- Gazebo Sensor Plugin -->
    <gazebo reference="lidar_link">
        <sensor name="lidar" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>5</update_rate>

            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14159</min_angle>  <!-- -180° -->
                        <max_angle>3.14159</max_angle>    <!-- +180° -->
                    </horizontal>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

    <!-- Camera Sensor -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>
    </link>

    <joint name="camera_joint" type="fixed">
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor type="camera" name="camera">
            <pose>0 0 0 0 0 0</pose>
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name="gazebo_ros_camera" filename="libgazebo_ros_camera.so">
                <cameraName>camera</cameraName>
            </plugin>
        </sensor>
    </gazebo>

    <!-- Existing wheels -->
    <xacro:scout_mini_wheel_1 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_1>

    <xacro:scout_mini_wheel_2 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_2>

    <xacro:scout_mini_wheel_3 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_3>

    <xacro:scout_mini_wheel_4 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_4>

    <xacro:include filename="$(arg urdf_extras)" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />

</robot>
